### ISSUE TITLE
How to activate with specific event data

### ISSUE THREAD

**Issue by MaxOhNoo** [allanf181/BPGE#3]
My use case is rocket league (https://overwolf.github.io/api/live-game-data/supported-games/rocket-league) and I want to only activate upon me scoring a goal, which requires the `local` event data.

Can I do this within a config file?

**Comment by allanf181** [comment]
You can use the [``teamGoal``](https://overwolf.github.io/api/live-game-data/supported-games/rocket-league#teamgoal-note) event

**Comment by allanf181** [comment]
> Oh well. Maybe the use of event data will be a feature in the future. Thanks!

I'm still planning this, including using these values to affect the vibration
